apiVersion: apps/v1
kind: Deployment
metadata:
  name: truancy-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: truancy-web
  template:
    metadata:
      labels:
        app: truancy-web
    spec:
      containers:
        - name: web
          image: ghcr.io/debjani-99/truancy-cloud:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              value: "postgresql://postgres:truancyCloud@truancy-postgres-svc:5432/mydb?schema=public"
            - name: NEXTAUTH_SECRET
              value: "truancy-cloud-demo-super-secret-change-me"
            - name: NEXTAUTH_URL
              value: "https://truancy-cloud-demo.nrp-nautilus.io"
            - name: UPLOAD_DIR
              value: "/tmp/uploads"
            - name: S3_ENDPOINT
              value: "https://s3-west.nrp-nautilus.io"
            - name: S3_BUCKET
              value: "secondbell-uploads"
            - name: S3_ACCESS_KEY
              value: "GIU1047JI72ZZ1ORFMK7"
            - name: S3_SECRET_KEY
              value: "1ULzKDC3pv3yc6luT9S32arOBqny0dj4oCZhyvSQ"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
